name: CI Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: System tests dependencies
      run: xargs -a system_test_requirements.txt sudo apt-get install
      working-directory: test_suite

    - name: Performance tests dependencies
      run: pip install -r python_requirements.txt
      working-directory: test_suite

    - name: System tests
      id: system-test
      run: ./system_tests.sh -c 0 -p 9999 3340 debug 0
      working-directory: test_suite
      continue-on-error: true

    - name: Upload system test logs
      uses: actions/upload-artifact@v4
      with:
        name: system-test-logs
        path: test_suite/logs/

    - name: Integrated tests
      run: go test -v ./test_suite/...

    - name: Fail job if system test failed (for clarity in GitHub UI)
      if: ${{ steps.system-test.outcome == 'failure' }}
      run: |
        exit 1