name: CI Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Set up simulated networks to test eduP2P with NAT
      run: ./setup_networks.sh 2 2
      working-directory: test_suite/nat_simulation

    - name: System tests
      id: system-test
      run: ./system_test.sh 9999 3340 debug "wg0:"
      working-directory: test_suite
      continue-on-error: true

    - name: Upload system test logs
      uses: actions/upload-artifact@v4
      with:
        name: system-test-logs
        path: test_suite/logs/

    - name: Integrated tests
      run: go test -v ./test_suite/...

    - name: Fail job if system test failed (for clarity in GitHub UI)
      if: ${{ steps.system-test.outcome == 'failure' }}
      run: |
        exit 1
